export type Visual = 'sat' | 'highlighter' | 'poker' | 'chat' | 'tabs';

export interface Project {
  name: string;
  tagline: string;
  description: string;
  period: string;
  stack: string[];
  visual: Visual;
  repo?: string;
  badge?: string;
}

export interface FeaturedProject extends Project {
  highlights: string[];
  stats: { value: string; label: string }[];
}

export const featured: FeaturedProject = {
  name: 'SatQuery AI',
  tagline: 'An agentic vision-language assistant for satellite imagery.',
  description:
    'Ask a question about a satellite image, a before-and-after pair or just a place on the map. An LLM controller routes it to the right specialist models, runs them, and answers only from their evidence, with an auditable trace of everything that ran.',
  highlights: [
    'Fine-tuned Grounding DINO for text-guided grounding and trained a U-Net for water-body segmentation on Kaggle GPUs.',
    'Change detection, optical–SAR fusion and a groundwater-potential score built on Google Earth Engine.',
    'FastAPI backend with a React, TypeScript and Leaflet interface.',
  ],
  stats: [
    { value: '6', label: 'specialist tools' },
    { value: '68', label: 'pytest tests' },
    { value: '0', label: 'pixels seen by the LLM' },
  ],
  period: 'Aug 2026',
  stack: ['Python', 'PyTorch', 'FastAPI', 'React', 'TypeScript', 'Earth Engine'],
  visual: 'sat',
  repo: 'https://github.com/Parixit007/SAT-AI',
};

export const projects: Project[] = [
  {
    name: 'The Greatest Code Highlighter',
    tagline: 'Colors on your code. That’s it.',
    description:
      'A VS Code extension for persistent highlights you can commit and share as plain JSON. Fuzzy matching keeps every highlight glued to its code through edits, pulls and branch switches.',
    period: 'Apr 2026 — now',
    stack: ['TypeScript', 'VS Code API'],
    visual: 'highlighter',
    repo: 'https://github.com/Parixit007/the-greatest-code-highlighter',
    badge: 'v0.1.0',
  },
  {
    name: 'Poker Bankroll',
    tagline: 'The bank for home poker nights.',
    description:
      'One laptop runs the game and everyone joins from their phone by scanning a QR code, generated by a QR encoder written from scratch. Zero dependencies, live totals, full undo.',
    period: 'Sep 2026',
    stack: ['Python', 'JavaScript'],
    visual: 'poker',
    repo: 'https://github.com/Parixit007/poker-bankroll',
  },
  {
    name: 'WhatsApp AI Bot',
    tagline: 'A personal assistant that lives in my chats.',
    description:
      'Runs on local LLMs through Ollama, with per-contact memory, image understanding, a whitelist for who it talks to, and owner commands sent by messaging myself.',
    period: 'Mar 2026',
    stack: ['Node.js', 'whatsapp-web.js', 'Ollama'],
    visual: 'chat',
    badge: 'Private',
  },
  {
    name: 'Declutter',
    tagline: 'Close the tabs you never meant to keep.',
    description:
      'A Chrome extension that clears stray new-tab pages and homepages with one click or a shortcut. Minimal permissions, and it never touches pinned or active tabs.',
    period: 'Dec 2025 — now',
    stack: ['JavaScript', 'Chrome Extensions'],
    visual: 'tabs',
    repo: 'https://github.com/Parixit007/Declutter',
  },
];
